// <auto-generated />
using DojoLeagueEF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace DojoLeagueEF.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20180821221846_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("DojoLeagueEF.Models.Dojo", b =>
                {
                    b.Property<int>("DojoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("DojoId");

                    b.ToTable("Dojos");
                });

            modelBuilder.Entity("DojoLeagueEF.Models.Ninja", b =>
                {
                    b.Property<int>("NinjaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("DojoId");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("NinjaId");

                    b.ToTable("Ninjas");
                });
#pragma warning restore 612, 618
        }
    }
}
